In [ ]:
import numpy as np

# Crear un conjunto de datos de ejemplo con valores entre 0 y 1
data = np.random.rand(1000, 10)  # 1000 muestras, 10 características

# Introducir valores faltantes de manera aleatoria
np.random.seed(0)  # Para reproducibilidad
missing_rate = 0.1  # 10% de los datos serán NaN
missing_indices = np.random.choice(data.size, int(data.size * missing_rate), replace=False)
data.ravel()[missing_indices] = np.nan


In [ ]:
data

array([[0.03982538, 0.07228576, 0.1711346 , ..., 0.32083684, 0.9861158 ,
               nan],
       [0.01743876, 0.46308825, 0.91032387, ..., 0.3658271 , 0.95692361,
        0.43061617],
       [0.63438624, 0.63708537, 0.64339339, ..., 0.32227436, 0.11368474,
        0.61024249],
       ...,
       [       nan,        nan, 0.57410623, ..., 0.57985432, 0.14963677,
        0.77394809],
       [       nan, 0.96589618, 0.27912795, ..., 0.55313806, 0.60292877,
        0.20646839],
       [0.43512049, 0.47039655, 0.16441548, ..., 0.98620729, 0.62292802,
        0.54041139]])

In [ ]:
from keras.models import Model
from keras.layers import Input, Dense

# Definir el autoencoder
input_dim = 10  # Número de características
encoding_dim = 5  # Tamaño de la capa de compresión

# Capa de entrada
input_layer = Input(shape=(input_dim,))

# Capa intermedia
encoded = Dense(encoding_dim, activation='relu')(input_layer)

# Capa de salida
decoded = Dense(input_dim, activation='linear')(encoded)

# Modelo del autoencoder
autoencoder = Model(input_layer, decoded)

# Compilar el modelo
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

# Datos para entrenar el autoencoder
# Aquí se usan los datos con valores faltantes
x_train = data[~np.isnan(data).any(axis=1)]  # Seleccionar solo filas sin NaN

# Entrenar el autoencoder
autoencoder.fit(x_train, x_train, epochs=50, batch_size=32, shuffle=True)


Epoch 1/50
12/12 [==============================] - 1s 3ms/step - loss: 0.4437
Epoch 2/50
12/12 [==============================] - 0s 3ms/step - loss: 0.3945
Epoch 3/50
12/12 [==============================] - 0s 3ms/step - loss: 0.3547
Epoch 4/50
12/12 [==============================] - 0s 3ms/step - loss: 0.3214
Epoch 5/50
12/12 [==============================] - 0s 3ms/step - loss: 0.2940
Epoch 6/50
12/12 [==============================] - 0s 4ms/step - loss: 0.2697
Epoch 7/50
12/12 [==============================] - 0s 3ms/step - loss: 0.2472
Epoch 8/50
12/12 [==============================] - 0s 3ms/step - loss: 0.2245
Epoch 9/50
12/12 [==============================] - 0s 3ms/step - loss: 0.2000
Epoch 10/50
12/12 [==============================] - 0s 3ms/step - loss: 0.1760
Epoch 11/50
12/12 [==============================] - 0s 3ms/step - loss: 0.1552
Epoch 12/50
12/12 [==============================] - 0s 3ms/step - loss: 0.1394
Epoch 13/50
12/12 [==============================

In [ ]:
# Preparar los datos con valores faltantes para la imputación
x_missing = data.copy()
x_missing

array([[0.03982538, 0.07228576, 0.1711346 , ..., 0.32083684, 0.9861158 ,
               nan],
       [0.01743876, 0.46308825, 0.91032387, ..., 0.3658271 , 0.95692361,
        0.43061617],
       [0.63438624, 0.63708537, 0.64339339, ..., 0.32227436, 0.11368474,
        0.61024249],
       ...,
       [       nan,        nan, 0.57410623, ..., 0.57985432, 0.14963677,
        0.77394809],
       [       nan, 0.96589618, 0.27912795, ..., 0.55313806, 0.60292877,
        0.20646839],
       [0.43512049, 0.47039655, 0.16441548, ..., 0.98620729, 0.62292802,
        0.54041139]])

In [ ]:
x_missing[np.isnan(data)] = 0  # Reemplazar NaN por 0 para la imputación

# Imputar los datos usando el autoencoder
imputed_data = autoencoder.predict(x_missing)

# Opcional: Reemplazar solo los valores faltantes en los datos originales
data[np.isnan(data)] = imputed_data[np.isnan(data)]



32/32 [==============================] - 0s 2ms/step


In [ ]:
data

array([[0.03982538, 0.07228576, 0.1711346 , ..., 0.32083684, 0.9861158 ,
        0.31672955],
       [0.01743876, 0.46308825, 0.91032387, ..., 0.3658271 , 0.95692361,
        0.43061617],
       [0.63438624, 0.63708537, 0.64339339, ..., 0.32227436, 0.11368474,
        0.61024249],
       ...,
       [0.36535776, 0.62190121, 0.57410623, ..., 0.57985432, 0.14963677,
        0.77394809],
       [0.37703389, 0.96589618, 0.27912795, ..., 0.55313806, 0.60292877,
        0.20646839],
       [0.43512049, 0.47039655, 0.16441548, ..., 0.98620729, 0.62292802,
        0.54041139]])

In [ ]:
x_missing

array([[0.03982538, 0.07228576, 0.1711346 , ..., 0.32083684, 0.9861158 ,
        0.        ],
       [0.01743876, 0.46308825, 0.91032387, ..., 0.3658271 , 0.95692361,
        0.43061617],
       [0.63438624, 0.63708537, 0.64339339, ..., 0.32227436, 0.11368474,
        0.61024249],
       ...,
       [0.        , 0.        , 0.57410623, ..., 0.57985432, 0.14963677,
        0.77394809],
       [0.        , 0.96589618, 0.27912795, ..., 0.55313806, 0.60292877,
        0.20646839],
       [0.43512049, 0.47039655, 0.16441548, ..., 0.98620729, 0.62292802,
        0.54041139]])

In [ ]:
data

array([[0.01053638, 0.95332285, 0.28091023, ..., 0.95380803, 0.86821043,
        0.48360226],
       [0.42171834, 0.98593723, 0.92187703, ..., 0.984519  , 0.30088927,
        0.32369538],
       [0.67204248, 0.89158604, 0.16239623, ..., 0.74398429, 0.6062905 ,
        0.37713842],
       ...,
       [0.59051871, 0.47189397, 0.91960836, ..., 0.47362884, 0.38347511,
        0.59855602],
       [0.42516166, 0.61455477, 0.72307906, ..., 0.02682991, 0.78655738,
        0.04415227],
       [0.05230784, 0.91606186, 0.25677426, ..., 0.12862271, 0.97560067,
        0.30632846]])

In [ ]:
imputed_data

array([[0.31538567, 0.4440121 , 0.32007483, ..., 0.41132188, 0.4250949 ,
        0.48360226],
       [0.48169148, 0.5885531 , 0.5217458 , ..., 0.5445213 , 0.46800596,
        0.65790695],
       [0.4756143 , 0.563111  , 0.5503214 , ..., 0.4061796 , 0.2662933 ,
        0.34482428],
       ...,
       [0.5905187 , 0.47189397, 0.62518877, ..., 0.542838  , 0.56242   ,
        0.55130774],
       [0.42516166, 0.5481314 , 0.49306536, ..., 0.37782648, 0.24406669,
        0.32190457],
       [0.21676514, 0.3391744 , 0.18638867, ..., 0.36150125, 0.46712083,
        0.44530076]], dtype=float32)